###
GET http://localhost:8080/api/csrf-token

###
POST http://localhost:8080/auth/login
Content-Type: application/json
X-CSRF-TOKEN: KltK8elwR7_Ae4r28iDReYRtDPM3eLyMnsKzW0oLjJzgsaSwHj4owdkScYbtS-uQkA3lT7FeIctTTN6h_ffVPXw4vfqE1ZbS


{
  "username": "u1",
  "password": "111"
}

###
GET http://localhost:8080/api/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1MSIsImlhdCI6MTc2MzAzMDA1NywiZXhwIjoxNzYzMTE2NDU3fQ.C3N_EfELPSYG7Cjln0c86LCbNQNh176g3MB51qGoHtM
X-CSRF-TOKEN: KltK8elwR7_Ae4r28iDReYRtDPM3eLyMnsKzW0oLjJzgsaSwHj4owdkScYbtS-uQkA3lT7FeIctTTN6h_ffVPXw4vfqE1ZbS


###
POST http://localhost:8080/api/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1MSIsImlhdCI6MTc2Mjk4ODY4MywiZXhwIjoxNzYzMDc1MDgzfQ.CnpJ-e_L00xJwFrLWXdvXkkHyuX5atRU_u7NT_myHvc
X-CSRF-TOKEN: KltK8elwR7_Ae4r28iDReYRtDPM3eLyMnsKzW0oLjJzgsaSwHj4owdkScYbtS-uQkA3lT7FeIctTTN6h_ffVPXw4vfqE1ZbS

{
  "name": "TEST"
}
