###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "u1",
  "password": "111"
}

###
GET http://localhost:8080/api/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1MSIsImlhdCI6MTc2Mjk4ODY4MywiZXhwIjoxNzYzMDc1MDgzfQ.CnpJ-e_L00xJwFrLWXdvXkkHyuX5atRU_u7NT_myHvc


###
POST http://localhost:8080/api/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1MSIsImlhdCI6MTc2Mjk4ODY4MywiZXhwIjoxNzYzMDc1MDgzfQ.CnpJ-e_L00xJwFrLWXdvXkkHyuX5atRU_u7NT_myHvc

{
  "name": "TEST"
}
